# Generated by Django 3.1.4 on 2021-02-05 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansplan',
            name='life_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plansplan',
            name='per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plansplan',
            name='per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plansplan',
            name='price_in_dollor',
            field=models.FloatField(default=0),
        ),
    ]
