# Generated by Django 3.1.4 on 2021-03-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansplan',
            name='fe',
            field=models.FloatField(default=0.0),
        ),
    ]
