# Generated by Django 3.1.4 on 2021-02-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210205_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansplan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
