# Generated by Django 3.1.4 on 2021-02-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_ad_llleft_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='llleft_views',
        ),
    ]
