# Generated by Django 3.1.4 on 2021-03-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_plansplan_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansplan',
            name='newfield',
        ),
    ]
