# Generated by Django 3.1.4 on 2021-03-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_plansplan_fe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansplan',
            name='fe',
        ),
    ]
