# Generated by Django 3.1.4 on 2021-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_plansplan_fe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansplan',
            name='fee',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
