# Generated by Django 3.1.4 on 2021-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210205_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansplan',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
