# Generated by Django 3.1.4 on 2021-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210207_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
