# Generated by Django 3.1.4 on 2021-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_adsplan_price_per_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsplan',
            name='price_per_1000',
        ),
    ]
